Repository WildCodeSchool/2023-09-PHP-LYON-P3-eclat-d-art, pull requests merged in 2024-01, with the labels that each got.

#19 Us01 s3 artwork form modif
  assets/images/logo-eclat.png
  migrations/Version20240104103412.php
  migrations/Version20240104104309.php
  migrations/Version20240104111632.php
  migrations/Version20240104131013.php
  src/Entity/Artwork.php
  src/Form/ArtworkType.php
Labels: Needs pair review

#20 modif type de champs date
  src/Form/ArtworkType.php
Labels: Needs pair review

#21 Us15 s3 upload img
  .gitignore
  assets/styles/app.scss
  composer.json
  composer.lock
  config/packages/vich_uploader.yaml
  migrations/Version20240104131934.php
  migrations/Version20240104141207.php
  src/DataFixtures/ArtworkFixtures.php
  src/DataFixtures/UserFixtures.php
  src/Entity/Artwork.php
  src/Form/ArtworkType.php
  templates/artwork/index.html.twig
  templates/artwork/indexByCategory.html.twig
  templates/artwork/show.html.twig
  templates/home/index.html.twig
Labels: Needs pair review

#22 initialisation user entity
  config/packages/security.yaml
  migrations/Version20240105085429.php
  migrations/Version20240105085714.php
  migrations/Version20240105091517.php
  src/Entity/Artwork.php
  src/Entity/User.php
  src/Repository/UserRepository.php
Labels: Needs pair review

#23 init fixtures + little change entity User
  migrations/Version20240105100202.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/_ArtworkFixtures.php
  src/Entity/Artwork.php
  src/Entity/User.php
Labels: Needs pair review

#24 Us05 2 s3 user login
  assets/styles/app.scss
  config/packages/security.yaml
  src/Controller/LoginController.php
  templates/_navbar.html.twig
  templates/login/index.html.twig
Labels: Changes requested

#25 debug final : form work + css
  assets/styles/app.scss
  config/packages/security.yaml
  src/DataFixtures/UserFixtures.php
Labels: Needs pair review

#29 sécurisation des routes + css sur formulaires
  assets/styles/app.scss
  config/packages/security.yaml
  src/Controller/ArtworkController.php
  src/Form/ArtworkType.php
  templates/_navbar.html.twig
  templates/artwork/edit.html.twig
  templates/artwork/index.html.twig
  templates/artwork/indexByCategory.html.twig
  templates/artwork/new.html.twig
Labels: Needs pair review

#30 rajout des ancres pour accéder aux images directement via la liste d…
  assets/styles/app.scss
  templates/artwork/indexByCategory.html.twig
Labels: Needs pair review

#27 SEO and accessibility adjustment
  assets/app.js
  assets/styles/app.scss
  templates/_navbar.html.twig
  templates/artwork/_delete_form.html.twig
  templates/artwork/_form.html.twig
  templates/artwork/index.html.twig
  templates/artwork/show.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Changes done

#32 Register
  assets/styles/app.scss
  config/routes.yaml
  migrations/Version20240110093344.php
  migrations/Version20240110112451.php
  src/Controller/RegistrationController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/_navbar.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Needs pair review

#34 Debug vich edit
  migrations/Version20240111090915.php
  src/Controller/ArtworkController.php
  src/Entity/Artwork.php
Labels: Needs pair review

#35 vich for user picture
  config/packages/vich_uploader.yaml
  migrations/Version20240110164154.php
  src/Entity/Artwork.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/registration/register.html.twig
Labels: Needs pair review

#33 new ancre
  templates/artwork/index.html.twig
Labels: Changes done

#37 change done
  assets/styles/app.scss
  templates/_navbar.html.twig
  templates/artwork/_delete_form.html.twig
  templates/artwork/index.html.twig
  templates/artwork/show.html.twig
Labels: Needs pair review

#38 Us08 s3 front page artist/index
  assets/images/facebook.png
  assets/images/instagram.png
  assets/images/pinterest.png
  assets/images/twitter.png
  assets/styles/app.scss
  src/Controller/UserController.php
  templates/home/index.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Changes requested

#42 modif path index home
  templates/home/index.html.twig
Labels: Needs pair review

#44 Test liip imagine bundle
  .gitignore
  composer.json
  composer.lock
  config/bundles.php
  config/packages/liip_imagine.yaml
  config/routes/liip_imagine.yaml
  config/services.yaml
  symfony.lock
  templates/artwork/index.html.twig
Labels: Needs pair review

#45 Us29 s3 change cards artiste oeuvre
  assets/styles/app.scss
  templates/_navbar.html.twig
  templates/artwork/index.html.twig
  templates/artwork/indexByCategory.html.twig
  templates/home/index.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Needs pair review

#46 Modif apparition button
  config/packages/liip_imagine.yaml
  templates/_navbar.html.twig
  templates/artwork/show.html.twig
Labels: Needs pair review

#47 tout est dans le titre
  assets/styles/app.scss
  public/media/cache/toto/uploads/images/posters/2109c59df90968d692a8619020c6028f-659eb1be9811f480045818.jpg
  public/media/cache/toto/uploads/images/posters/440d087d885d22c376e115b69aa4fdb8-659d6eca7a500151586105.jpg
  public/media/cache/toto/uploads/images/posters/546c9918-097a-4e16-b149-7ca4f653587d-65a004e7d5f19232535968.jpg
  public/media/cache/toto/uploads/images/posters/6b7bddb1-167a-4ada-b0b6-127d65ef1bc0-659eb20ab1b9c374908478.jpg
  public/media/cache/toto/uploads/images/posters/ba3b2a2c7ab20cefbeecba82433bebd5-659d6e7ba8094262170788.jpg
  public/media/cache/toto/uploads/images/posters/bustes-grecs-casses-au-sol-659d6e971cb3e177283824.jpg
  public/media/cache/toto/uploads/images/posters/delapartdieu-659fc83471de3902592243.png
  public/media/cache/toto/uploads/images/posters/f983aee2ca220c8df1c3fcc6529a6bc0-659eace27c20f765727977.jpg
  public/media/cache/toto/uploads/images/posters/pexels-eduardo-romero-1707640-65a66b26f3b21814851416.jpg
  public/media/cache/toto/uploads/images/posters/pexels-ian-turnell-709552-659eb23411a33189379261.jpg
  public/media/cache/toto/uploads/images/posters/pexels-james-wheeler-1486974-65a00530ab6d0885939790.jpg
  public/media/cache/toto/uploads/images/posters/pexels-sebastian-palomino-1955134-659ff54b7e8b0720710639.jpg
  public/media/cache/toto/uploads/images/posters/pexels-zack-jarosz-1727658-659fcb96367da339584654.jpg
  public/media/cache/toto/uploads/images/posters/tab-4-659ec3d3074dd235473568.jpeg
Labels: Needs pair review

#48 Us31 s3 mini slide artwork
  public/media/cache/toto/uploads/images/posters/2109c59df90968d692a8619020c6028f-659eb1be9811f480045818.jpg
  public/media/cache/toto/uploads/images/posters/440d087d885d22c376e115b69aa4fdb8-659d6eca7a500151586105.jpg
  public/media/cache/toto/uploads/images/posters/546c9918-097a-4e16-b149-7ca4f653587d-65a004e7d5f19232535968.jpg
  public/media/cache/toto/uploads/images/posters/6b7bddb1-167a-4ada-b0b6-127d65ef1bc0-659eb20ab1b9c374908478.jpg
  public/media/cache/toto/uploads/images/posters/ba3b2a2c7ab20cefbeecba82433bebd5-659d6e7ba8094262170788.jpg
  public/media/cache/toto/uploads/images/posters/bustes-grecs-casses-au-sol-659d6e971cb3e177283824.jpg
  public/media/cache/toto/uploads/images/posters/delapartdieu-659fc83471de3902592243.png
  public/media/cache/toto/uploads/images/posters/f983aee2ca220c8df1c3fcc6529a6bc0-659eace27c20f765727977.jpg
  public/media/cache/toto/uploads/images/posters/pexels-eduardo-romero-1707640-65a66b26f3b21814851416.jpg
  public/media/cache/toto/uploads/images/posters/pexels-ian-turnell-709552-659eb23411a33189379261.jpg
  public/media/cache/toto/uploads/images/posters/pexels-james-wheeler-1486974-65a00530ab6d0885939790.jpg
  public/media/cache/toto/uploads/images/posters/pexels-sebastian-palomino-1955134-659ff54b7e8b0720710639.jpg
  public/media/cache/toto/uploads/images/posters/pexels-zack-jarosz-1727658-659fcb96367da339584654.jpg
  public/media/cache/toto/uploads/images/posters/tab-4-659ec3d3074dd235473568.jpeg
  src/Controller/ArtworkController.php
  src/Controller/UserController.php
  src/Repository/ArtworkRepository.php
  templates/artwork/index.html.twig
  templates/artwork/indexByCategory.html.twig
  templates/artwork/show.html.twig
  templates/home/index.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Needs pair review

#49 Us33 s3 random artiste home page
  assets/app.js
  assets/styles/app.scss
  src/Controller/HomeController.php
  src/Controller/UserController.php
  templates/home/index.html.twig
  templates/user/index.html.twig
Labels: Needs pair review

#50 User edit
  assets/styles/app.scss
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/_navbar.html.twig
  templates/artwork/show.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/show.html.twig
Labels: Needs pair review

#52 Us35 s3 user avatar
  assets/styles/app.scss
  src/Controller/ArtworkController.php
  templates/artwork/show.html.twig
Labels: Changes requested

#53 Us34 s3 icon rs
  assets/app.js
  assets/images/x.avif
  assets/styles/app.scss
  composer.json
  composer.lock
  src/Controller/UserController.php
  templates/base.html.twig
  templates/user/show.html.twig
Labels: Needs pair review

#54 Social network link
  assets/styles/app.scss
  migrations/Version20240122132822.php
  src/Entity/User.php
  src/Form/UserType.php
  templates/user/show.html.twig
Labels: Needs pair review

#55 font change
  assets/styles/app.scss
  templates/base.html.twig
Labels: Needs pair review

#57 Entity and if login
  migrations/Version20240124095743.php
  src/Entity/Artwork.php
  src/Form/ArtworkType.php
  templates/artwork/show.html.twig
  templates/login/index.html.twig
Labels: Needs pair review

#59 connexion bug fixed
  src/Entity/User.php
Labels: Needs pair review

#58 Us35 s04 admin dashboard
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/uid.yaml
  intl.php
  src/Controller/Admin/ArtworkCrudController.php
  src/Controller/Admin/CategoryCrudController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/UserCrudController.php
  src/DataFixtures/ArtworkFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/_ArtworkFixtures.php
  src/Entity/Artwork.php
  src/Entity/User.php
  src/Repository/UserRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
Labels: Needs pair review, Changes done

#61 Page 404 error
  assets/images/error.jpeg
  templates/bundles/TwigBundle/Exception/error404.html.twig
Labels: Needs pair review

#60 separation dans la navbar de l'inscription et de la connexion
  templates/_navbar.html.twig
Labels: Changes done

#64 Image to webp
  config/packages/liip_imagine.yaml
Labels: Needs pair review

#66 delete ID on admin dashboard
  src/Controller/Admin/ArtworkCrudController.php
  src/Controller/Admin/UserCrudController.php
Labels: Changes done

#69 User button redirect to the user profile
  templates/_navbar.html.twig
  templates/user/index.html.twig
Labels: Needs pair review

#70 change color button
  src/Form/ArtworkType.php
  templates/artwork/_form.html.twig
  templates/artwork/show.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Needs pair review

#71 modif faites
  src/Controller/UserController.php
  templates/_navbar.html.twig
Labels: Needs pair review

#72 modif redirect sur registration
  src/Controller/RegistrationController.php
Labels: Needs pair review

#73 Us55 s04 message flash comfirmation login
  assets/app.js
  assets/flashMessage.js
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Needs pair review

#75 plus d'admin dans la liste des artistes
  templates/user/index.html.twig
Labels: Needs pair review

#76 Us54 s04 message flash creation de compte
  assets/flashMessage.js
  src/Controller/ArtworkController.php
  src/Controller/RegistrationController.php
  src/Controller/UserController.php
  templates/artwork/index.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/user/index.html.twig
Labels: Changes done

#77 chang
  templates/artwork/_delete_form.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
Labels: Needs pair review

#79 date auto et footer restyliser
  assets/styles/app.scss
  templates/_footer.html.twig
  templates/base.html.twig
Labels: Needs pair review

#82 Us27 s3 dimensions images
  assets/styles/app.scss
  composer.lock
  config/packages/liip_imagine.yaml
  src/Controller/HomeController.php
  templates/artwork/_delete_form.html.twig
  templates/artwork/index.html.twig
  templates/home/index.html.twig
Labels: Changes done

#83 modif des aria et meta en anglais
  templates/_navbar.html.twig
  templates/artwork/_delete_form.html.twig
  templates/artwork/_form.html.twig
  templates/artwork/show.html.twig
  templates/home/index.html.twig
  templates/registration/register.html.twig
Labels: Changes done

#85 Us66 s04 fix flash message
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Changes done

#86 Us67 s04 no admin in url show
  src/Controller/UserController.php
Labels: Needs pair review

#87 Us67 s04 barre de recherche oeuvres
  assets/styles/app.scss
  src/Controller/ArtworkController.php
  src/Repository/ArtworkRepository.php
  templates/artwork/index.html.twig
  templates/artwork/search/_form.html.twig
  templates/artwork/search/results.html.twig
Labels: Changes done

#88 alert message in my condition
  src/Controller/UserController.php
Labels: Needs pair review

#89 magnifying glass disappears
  assets/app.js
Labels: Needs pair review

#92 Bug delete
  src/Controller/UserController.php
Labels: Needs pair review

#91 classement des images par date d'upload
  src/Controller/ArtworkController.php
  src/Repository/ArtworkRepository.php
Labels: Changes done

#90 erreur branch
  assets/styles/app.scss
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: Needs pair review

#97 Us71 s04 mini slide
  assets/app.js
  assets/styles/app.scss
  templates/artwork/show.html.twig
Labels: Changes done
